// Emits `src/version.generated.ts` with the plugin coordinate the extension
// auto-injects via Gradle, so the extension always asks for a plugin version it
// has actually been built against.
//
// Version resolution:
//   - `PLUGIN_VERSION` env var — release builds set this from the tag, and a
//     local dev loop sets it to a mavenLocal SNAPSHOT (`1.46.3-SNAPSHOT`) to
//     test against an unpublished plugin.
//   - else, `composeAiPlugin` from `plugin-version.json` — the committed
//     compatibility pin.
//
// This used to derive a next-patch SNAPSHOT from the monorepo's
// `.release-please-manifest.json`. That was correct while the plugin and the
// extension were one repo cutting one version: "the plugin built alongside me"
// was a fact the checkout could answer. It cannot answer that any more. The
// extension is now a consumer of a *released* plugin, so the default is the
// pinned release and reaching a SNAPSHOT is the explicit, opt-in case.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pinPath = resolve(here, "../plugin-version.json");
const outPath = resolve(here, "../src/version.generated.ts");

const envOverride = process.env.PLUGIN_VERSION;

function pinnedVersion() {
    const pin = JSON.parse(readFileSync(pinPath, "utf8"));
    const version = pin.composeAiPlugin;
    if (typeof version !== "string" || version.length === 0) {
        throw new Error(
            `could not read "composeAiPlugin" from ${pinPath} — the extension has no plugin coordinate to inject`,
        );
    }
    // Shape-check the pin rather than trusting it. A malformed pin bakes a
    // coordinate that resolves to nothing, and the failure surfaces to a user
    // as an unexplained Gradle resolution error long after this ran.
    if (!/^\d+\.\d+\.\d+(-SNAPSHOT)?$/.test(version)) {
        throw new Error(
            `unexpected version shape in ${pinPath}: "${version}" (need MAJOR.MINOR.PATCH[-SNAPSHOT])`,
        );
    }
    return version;
}

const resolved =
    envOverride && envOverride.length > 0 ? envOverride : pinnedVersion();

const body = `// Generated by scripts/generate-version.mjs at compile time.
// Source of truth: PLUGIN_VERSION env (release / local SNAPSHOT loop) or the
// \`composeAiPlugin\` pin in plugin-version.json. Do not edit by hand — the file
// is rewritten on every \`npm run compile\` and is gitignored.
export const BUNDLED_PLUGIN_VERSION = "${resolved}";
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);
console.log(
    `generate-version: BUNDLED_PLUGIN_VERSION=${resolved} → ${outPath}`,
);
