// Emits `src/version.generated.ts` with the plugin coordinate the extension
// auto-injects via Gradle. Mirrors `cli/build.gradle.kts:generateCliVersionResource`,
// which bakes the equivalent version into the CLI jar — so the extension always
// asks for the plugin version it was built alongside, with no drift between
// the bundled coordinate and what got published.
//
// Version resolution:
//   - `PLUGIN_VERSION` env var (release builds set this from the tag)
//   - else, next-patch SNAPSHOT derived from `.release-please-manifest.json`
//     (matches `build-logic/...ComposeAiMavenPublishingPlugin.kt`'s fallback,
//     so an F5 dev loop publishes and the extension asks for the same coord)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const manifestPath = resolve(here, "../../.release-please-manifest.json");
const outPath = resolve(here, "../src/version.generated.ts");

const envOverride = process.env.PLUGIN_VERSION;

function nextPatchSnapshot(current) {
    const parts = current.split(".").map((p) => Number.parseInt(p, 10));
    if (parts.length !== 3 || parts.some(Number.isNaN)) {
        throw new Error(
            `unexpected version shape in ${manifestPath}: "${current}" (need MAJOR.MINOR.PATCH)`,
        );
    }
    const [major, minor, patch] = parts;
    return `${major}.${minor}.${patch + 1}-SNAPSHOT`;
}

const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const manifestVersion = manifest["."];
if (!manifestVersion) {
    throw new Error(`could not read "." version from ${manifestPath}`);
}

const resolved =
    envOverride && envOverride.length > 0
        ? envOverride
        : nextPatchSnapshot(manifestVersion);

const body = `// Generated by scripts/generate-version.mjs at compile time.
// Source of truth: PLUGIN_VERSION env (release) or .release-please-manifest.json
// (next-patch SNAPSHOT for local dev). Do not edit by hand — the file is
// rewritten on every \`npm run compile\` and is gitignored.
export const BUNDLED_PLUGIN_VERSION = "${resolved}";
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);
console.log(
    `generate-version: BUNDLED_PLUGIN_VERSION=${resolved} → ${outPath}`,
);
